@startuml
left to right direction

actor ":Usuario:" as User
actor ":Serviço Supabase Auth:" as ServicoSupabaseAuth <<Serviço Externo>>
actor ":Serviço UOL Notícias:" as ServicoUolApi <<Serviço Externo>>


rectangle "Blue Bee App" {
    usecase "Autenticar Usuário" as UC_Auth
    usecase "Iniciar Tutorial" as UC_Tutorial
    usecase "Ver Perfil" as UC_VerPerfil
    usecase "Exibir Notícias e Eventos do Mercado" as UC_ExibirNoticias
    usecase "Exibir Feedback Personalizado" as UC_ExibirFeedback
    usecase "Gerenciar Ativos da Carteira" as UC_GerenciarAtivosCarteira
    usecase "Simular Investimentos" as UC_SimularInvestimentos
    usecase "Completar Desafios" as UC_CompletarDesafios
    usecase "Iniciar Quiz" as UC_IniciarQuiz
    usecase "Ver Glossário" as UC_VerGlossario
    usecase "Editar perfil" as UC_EditPerfil
    usecase "Sair da conta" as UC_SairConta
}

User -- UC_Auth
User -- UC_Tutorial
User -- UC_VerPerfil
User -- UC_ExibirNoticias
User -- UC_ExibirFeedback
User -- UC_GerenciarAtivosCarteira
User -- UC_SimularInvestimentos
User -- UC_CompletarDesafios
User -- UC_IniciarQuiz
User -- UC_VerGlossario

UC_VerPerfil <. UC_EditPerfil : <<extends>>
UC_VerPerfil <. UC_SairConta : <<extends>>

UC_Auth -- ServicoSupabaseAuth
UC_ExibirNoticias -- ServicoUolApi

@enduml