@startuml
left to right direction
:Usuario:

rectangle "Blue Bee App" {
    usecase "Onboarding Didático Interativo" as C1
    usecase "Manter Dados" as C2
    usecase "Exibir Notícias e Eventos do Mercado" as C3
    usecase "Exibir Feedback Personalizado" as C4
    usecase "Manter ativos" as C5
    usecase "Simular Investimentos" as C6
    usecase "Completar Desafios" as C7
    usecase "Manter Quiz" as C8
    usecase "Manter Glossário" as C9
    usecase "Manter Configurações" as C10
    usecase "Manter Amigos" as C11
}

:Uol:
:Brapi:

Usuario -- C1
Usuario --> C2
Usuario --> C3
Usuario --> C4
Usuario --> C5
Usuario --> C6
Usuario --> C7
Usuario --> C8
Usuario --> C9
Usuario --> C10
Usuario --> C11

C3 -- Uol

C5 -- Brapi
C6 -- Brapi

@enduml
