@startuml

entity Usuario {
    + id: UUID
    + nome: String
    + email: String
    + senha: String
    + perfil_investidor: String
    + nivel: Integer
    + data_nascimento: Date
    + genero: String
}

' isso no banco nao existe
entity Carteira {
    + id: UUID
    + saldo_atual: Decimal
    + rentabilidade_total: Decimal
    + usuario_id: UUID
}

entity Ativo {
    + id: UUID
    + nome: String
    + tipo: String
    + risco: String
    + descricao: String
}

entity AtivoCarteira {
    + id: UUID
    + carteira_id: UUID
    + ativo_id: UUID
    + quantidade: Decimal
    + preco_medio: Decimal
}

' isso pode ser o historico
entity Transacao {
    + id: UUID
    + tipo: String
    + valor: Decimal
    + data: Date
    + carteira_id: UUID
    + ativo_id: UUID
}

entity Desafio {
    + id: UUID
    + titulo: String
    + descricao: String
    + recompensa: String
}

entity DesafioUsuario {
    + id: UUID
    + usuario_id: UUID
    + desafio_id: UUID
    + status: String
    + data_conclusao: Date
}

entity Glossario {
    + id: UUID
    + termo: String
    + definicao: String
}

entity Favorito {
    + id: UUID
    + usuario_id: UUID
    + glossario_id: UUID
}

' sem pq isso é os desafios
entity Conquista {
    + id: UUID
    + titulo: String
    + descricao: String
    + icone: String
}
' esse aqui tambem
entity UsuarioConquista {
    + id: UUID
    + usuario_id: UUID
    + conquista_id: UUID
    + data_conquista: Date
}

entity RelatorioProgresso {
    + id: UUID
    + usuario_id: UUID
    + topicos_aprendidos: String
    + erros_comuns: String
    + tempo_no_app: String
}

' sem
entity Notificacao {
    + id: UUID
    + usuario_id: UUID
    + mensagem: String
    + data_envio: Date
    + lida: Boolean
}

' que que é isso?
entity Atalho {
    + id: UUID
    + usuario_id: UUID
    + nome: String
    + destino: String
}


Usuario ||--o{ Carteira : possui
Carteira ||--o{ AtivoCarteira : possui
Ativo ||--o{ AtivoCarteira : compõe
Carteira ||--o{ Transacao : realiza
Ativo ||--o{ Transacao : movimenta

Usuario ||--o{ DesafioUsuario : realiza
Desafio ||--o{ DesafioUsuario : é_realizado
Usuario ||--o{ QuizUsuario : responde
Quiz ||--o{ QuizUsuario : é_respondido

Usuario ||--o{ Favorito : favorita
Glossario ||--o{ Favorito : é_favoritado

Usuario ||--o{ UsuarioConquista : conquista
Conquista ||--o{ UsuarioConquista : é_conquistada

Usuario ||--o{ RelatorioProgresso : gera
Usuario ||--o{ Ranking : aparece_em
Usuario ||--o{ Convite : envia
Usuario ||--o{ Amizade : amigo
Usuario ||--o{ Notificacao : recebe
Usuario ||--o{ Atalho : possui
Usuario ||--o{ EstatisticaQuiz : estatistica

@enduml