@startuml

title Adicionar Amigos (Loop Corrigido)

|Usuário|
start
repeat
    :Preencher ID do Amigo a ser adicionado;
|Sistema|
    :Sistema Verifica se ID do Amigo Existe;
repeat while (ID do Amigo Existe no Sistema?) is (Não)
:Envia Pedido de Amizade para o Amigo encontrado;
stop

@enduml