@startuml

title Sistema Busca Dados da Brapi

|Sistema|
start
:Verificar/Obter Chave de Acesso para API Brapi;
if (Chave de Acesso Válida?) then (Sim)
    :Conectar à API da Brapi;
    :Requisitar Dados de Ativos/Mercado;
    :Receber Dados da Brapi;
    :Processar/Armazenar Dados Recebidos;
    :Sinalizar que novos dados de mercado estão disponíveis;
else (Não)
    :Registrar falha na obtenção da chave/acesso;
endif
stop

@enduml