@startuml

sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

title Cadastrar-se

|Usuário|
start
if(Entrar com o Google?) then (Não)
    :Preencher Nome;
    :Preencher Gênero;
    :Preencher Data de Nascimento;
    :Preencher Email;
    :Preencher Senha;
    :Preencher Confirmar Senha;
else (Sim)
endif
|Sistema|
:Usuário]

@enduml