@startuml

title Exibir Feedback Personalizado (Revisado)

|Sistema|
start
:Carrega Estatísticas de Investimento do Usuário;
:Carrega Progresso em Quiz do Usuário;
:Analisa os dados e Gera Recomendações/Insights;
:Prepara Feedback Personalizado para exibição;
|Usuário|
:Visualiza Feedback Personalizado e Recomendações;
stop

@enduml