@startuml

sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

title Gerenciar Configurações

|Usuário|
start
|Sistema|
:Inicia Usuário <$rake>;
if(Mudar de Tema?) then (Sim)
    repeat
    |Usuário|
    :Seleciona Tema;
    repeat while (Tema Selecionado?) is (Não) not (Sim)
    |Sistema|
    :Atualiza Tema Atual para o Pedido;
else (Não)
endif
if(Mudar Velocidade?) then (Sim)
    repeat
    |Usuário|
    :Seleciona Velocidade;
    repeat while (Tema Selecionado?) is (Não) not (Sim)
    |Sistema|
    :Atualiza Velocidade Atual para a Pedida;
else (Não)
endif
if(Desativar/Ativar Som?) then (Sim)
    |Sistema|
    :Atualiza o Som Sendo o Contrário ao Estado Atual;
else (Não)
endif
if(Desativar/Ativar Notificações?) then (Sim)
    |Sistema|
    :Atualiza as Notificações Sendo o Contrário ao Estado Atual;
else (Não)
endif
stop

@enduml