@startuml

title Gerenciar Pedidos (Rótulos Corrigidos)

|Usuário|
start
|Sistema|
:Inicia Usuário;
|Usuário|
:Seleciona Aceitar ou Recusar Pedido;
|Sistema|
if(Pedido Aceito?) then (Sim)
    :Adiciona Amigo a Lista de Amigos;
else (Não)
endif
:Remove Pedido da lista de pendentes;
:Apresenta Lista de Pedidos atualizada;
stop

@enduml