@startuml

sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

title Iniciar Quiz

|Usuário|
start
|Sistema|
:Inicia Usuário <$rake>;
if(Novo Dia?) then (Sim)
    :Remove Todos os Quizes da Lista de Quizes Diários;
    :Adiciona Novos Quizes á Lista de Quizes Diários;
else (Não)
endif
repeat
    |Usuário|
    :Seleciona Alternativa;
    |Sistema|
    if(Acertou?) then (Sim)
        :Adiciona Pontos de Experiência ao Tema da Questão;
        note right
            <b>Exemplo:<b> 10 Pontos 
        end note
    else (Não)
        :Adiciona Menos Pontos de Experiência ao Tema da Questão;
        note left
            <b>Exemplo:<b> 3 Pontos 
        end note
    endif
repeat while (Quiz Concluido?) is (Nao) not (Sim)
:Calcula Porcentagem de Acertos por Questoes;
:Atualiza as Estátisticas de Progresso em Quiz;
:Adiciona Saldo ou Ativo ao Usuário;
|Usuário|
:Porcentagem de Acertos]
:Estatisticas de Progresso em Quiz]
:Saldo ou Ativos]
stop

@enduml