@startuml

sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

title Iniciar Quiz

|Usuário|
start
|Sistema|
:Seleciona 6 Questões aleatórias da Lista de Quiz;
repeat
    |Usuário|
    :Seleciona Alternativa;
    |Sistema|
    if(Acertou?) then (Sim)
        :Adiciona Pontos de Experiência ao Tema da Questão;
        note right
            <b>Exemplo:<b> 1 Pontos 
        end note
    else (Não)
        :Adiciona Zero Pontos de Experiência ao Tema da Questão;
        note left
            <b>Exemplo:<b> 0 Pontos
        end note
    endif
repeat while (Quiz Concluido?) is (Nao) not (Sim)
:Calcula Porcentagem de Acertos;
|Usuário|
:Porcentagem de Acertos]
:Link para Tema com menos pontos;
note right
    <b>Exemplo:<b> Glossário 
end note
stop

@enduml