@startuml

title Login (com Autenticação Firebase)

|Usuário|
start
repeat
    :Preencher Email e Senha;
|Sistema|
    :Solicitar Autenticação ao Firebase(Email, Senha);
    note right
        Sistema interage com
        o serviço Firebase
        para validar as credenciais.
    end note
repeat while (Firebase autenticou com sucesso?) is (Não) not (Sim)
stop

@enduml