@startuml

title Login com Autenticação Firebase (Revisado)

|Usuário|
start
repeat
    :Preencher Email e Senha na tela de login;
    :Clica no botão "Entrar";
|Sistema|
    :Solicitar Autenticação ao Serviço Firebase (com Email e Senha fornecidos);
repeat while (Firebase autenticou com sucesso?) is (Não)

:Direcionar usuário para a tela principal do aplicativo (Dashboard);
stop

@enduml