@startuml

sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

title Simular Investimentos

|Usuário|
start
|Usuário|
repeat
    :Preencher Valor Inicial;
    :Preencher Aporte Mensal;
    :Preencher Periodo de Aplicação (Anos);
    :Preencher Rentabilidade Anual Estimada (%);
    :Selecionar Indexador Base;
    note right
        Nenhum (usar rentabilidade acima)
        ====
        CDI (11,25% a.a.)
        ====
        Poupança (6,17% a.a.)
        ====
        Tesouro Selic (10,76% a.a.)
        ====
        Tesouro IPCA (9,50% a.a. + IPCA)
    end note
    |Sistema|
repeat while(Todas Informações Foram Preenchidas?) is (Não) not (Sim)
:Calcula Montante Final;
stop

@enduml