@startuml

title Ver Glossário (Rótulos Corrigidos)

|Usuário|
start
|Sistema|
:Inicia Usuário;
|Usuário|
:Preencher Buscar;
|Sistema|
if(Buscar Vazio?) then (Não)
    :Busca Correspondência;
    if(Existe Correspondência?) then (Sim)
        :Palavras correspondentes;
    else (Não)
    endif
else (Sim)
    :Todas as Palavras;
endif
|Usuário|
:Lista de Palavras;
stop

@enduml