@startuml

sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

title Completar Desafios

|Usuário|
start
|Sistema|
:Inicia Usuário <$rake>;
:Carrega Desafios]

if(Desafios Concluidos?) then (Sim)
    :Adiciona Saldo ou Ativo ao Usuário;
    :Adiciona desafio a lista Desafio_Usuário;
else (Não)
endif
|Usuário|
:Lista de Desafios]
stop

@enduml