@startuml

title Diagrama de Sequência: Exibir Notícias do Mercado

actor ":Usuario" as User
participant ":TelaPrincipal" as Tela
participant ":NoticiaController" as Controller
participant ":ServicoUol" as UolApi

User -> Tela: Acessa Tela Principal (ou Seção de Notícias)
activate Tela

Tela -> Controller: carregarNoticiasDoMercado()
activate Controller

Controller -> UolApi: buscarUltimasNoticias()
activate UolApi
UolApi --> Controller: dadosBrutosNoticias
deactivate UolApi

Controller -> Controller: processarEFormatarNoticias(dadosBrutosNoticias)
activate Controller
Controller --> Controller: listaNoticiasProntas
deactivate Controller

Controller --> Tela: exibirListaDeNoticias(listaNoticiasProntas)
deactivate Controller

Tela --> User: Mostra Notícias do Mercado
deactivate Tela

@enduml